# Generated by Django 5.0.6 on 2024-07-05 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Место"
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        verbose_name="Время, когда необходимо выполнять привычку"
                    ),
                ),
                ("action", models.CharField(max_length=50, verbose_name="Действие")),
                (
                    "is_enjoyable",
                    models.BooleanField(
                        default=False, verbose_name="Признак приятной привычки"
                    ),
                ),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("Раз в день", "Раз в день"),
                            ("Раз в два дня", "Раз в два дня"),
                            ("Раз в три дня", "Раз в три дня"),
                            ("Раз в четыре дня", "Раз в четыре дня"),
                            ("Раз в пять дней", "Раз в пять дней"),
                            ("Раз в шесть дней", "Раз в шесть дней"),
                            ("Раз в неделю", "Раз в неделю"),
                        ],
                        default="Раз в день",
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Время на выполнение привычки",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="Признак публичности",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель привычки",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_to_habit",
                        to="habits.habit",
                        verbose_name="Родительская привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
