# Generated by Django 5.0.6 on 2024-07-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_remove_habit_creator_habit_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="tg_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Telegram_chat_id"
            ),
        ),
    ]
