# Generated by Django 5.0.6 on 2024-07-07 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_habit_tg_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="tg_id",
        ),
    ]
